### ISSUE TITLE
Leaderboard - reach/optional

### ISSUE THREAD

**Issue by currymich** [currymich/winter-challenge#2]
Have a leaderboard for landing page?

**Comment by currymich** [comment]
Leaderboard with individuals removed, decided to not pursue

**Comment by currymich** [comment]
Idea from Anna - Add more info to user model, leaderboard based on class or gender??

This could work with a separate profile page where they can add more details but wont be able to do this with existing user model/reg process

**Comment by parkben01** [comment]
Let's not do that.

**Comment by currymich** [comment]
Added leaderboard based on class and gender to landing page
